### ISSUE TITLE
支持代理否？

### ISSUE THREAD

**Issue by plutoid** [SeanGong/wechatrobot#1]
Hi,

因为向机器人发送消息时需要经过http代理服务器，所以有这个问题，谢谢！

**Comment by plutoid** [comment]
简单硬编码加了些代理的代码，比较丑也能work。


./api/wechat.go

        proxy,_:= url.Parse("http://10.203.92.125:8080")
        tr := &http.Transport{
                Proxy: http.ProxyURL(proxy),
                TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
        }

        client := &http.Client{ Transport: tr, Timeout: time.Second *5,}

**Comment by seangong** [comment]
机器人放在代理后面，这个是不不支持这种代理的。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Tian, Hua ***@***.***>
发送时间: Friday, September 30, 2022 1:24:23 AM
收件人: SeanGong/wechatrobot ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [SeanGong/wechatrobot] 支持代理否？ (Issue #1)


简单硬编码加了些代理的代码，比较丑也能work。

    proxy,_:= url.Parse("http://10.203.92.125:8080")

    tr := &http.Transport{

            Proxy: http.ProxyURL(proxy),

            TLSClientConfig: &tls.Config{InsecureSkipVerify: true},

    }



    client := &http.Client{ Transport: tr, Timeout: time.Second *5,}



―

**Comment by seangong** [comment]
你可以把代码改造一下就行了。我这个是直接给企业微信群机器人发送消息。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: sean gong ***@***.***>
发送时间: Saturday, October 1, 2022 4:08:17 PM
收件人: SeanGong/wechatrobot ***@***.***>; SeanGong/wechatrobot ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [SeanGong/wechatrobot] 支持代理否？ (Issue #1)

机器人放在代理后面，这个是不不支持这种代理的。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Tian, Hua ***@***.***>
发送时间: Friday, September 30, 2022 1:24:23 AM
收件人: SeanGong/wechatrobot ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [SeanGong/wechatrobot] 支持代理否？ (Issue #1)


简单硬编码加了些代理的代码，比较丑也能work。

    proxy,_:= url.Parse("http://10.203.92.125:8080")

    tr := &http.Transport{

            Proxy: http.ProxyURL(proxy),

            TLSClientConfig: &tls.Config{InsecureSkipVerify: true},

    }



    client := &http.Client{ Transport: tr, Timeout: time.Second *5,}



―

**Comment by seangong** [comment]
这个代理功能后续考虑加上去。谢了。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: sean gong ***@***.***>
发送时间: Saturday, October 1, 2022 4:10:43 PM
收件人: SeanGong/wechatrobot ***@***.***>; SeanGong/wechatrobot ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [SeanGong/wechatrobot] 支持代理否？ (Issue #1)

你可以把代码改造一下就行了。我这个是直接给企业微信群机器人发送消息。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: sean gong ***@***.***>
发送时间: Saturday, October 1, 2022 4:08:17 PM
收件人: SeanGong/wechatrobot ***@***.***>; SeanGong/wechatrobot ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [SeanGong/wechatrobot] 支持代理否？ (Issue #1)

机器人放在代理后面，这个是不不支持这种代理的。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Tian, Hua ***@***.***>
发送时间: Friday, September 30, 2022 1:24:23 AM
收件人: SeanGong/wechatrobot ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [SeanGong/wechatrobot] 支持代理否？ (Issue #1)


简单硬编码加了些代理的代码，比较丑也能work。

    proxy,_:= url.Parse("http://10.203.92.125:8080")

    tr := &http.Transport{

            Proxy: http.ProxyURL(proxy),

            TLSClientConfig: &tls.Config{InsecureSkipVerify: true},

    }



    client := &http.Client{ Transport: tr, Timeout: time.Second *5,}



―

**Comment by seangong** [comment]
代理功能已加。

**Comment by plutoid** [comment]
👍
